import { CustomerApiKey } from '../models/customerApiKey'
import { CustomerApiKeyEncryption } from '../utils/customerApiKeyEncryption'
import { PutCommand, type DynamoDBDocumentClient } from '@aws-sdk/lib-dynamodb'
import { type APIGatewayClient, CreateApiKeyCommand, type CreateApiKeyCommandInput, CreateUsagePlanKeyCommand, type CreateUsagePlanKeyRequest } from '@aws-sdk/client-api-gateway'

import crypto from 'crypto'

class CreateCustomerApiKeyService {
  static CLIENT_ID_CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
  static CLIENT_ID_LENGTH = 17
  static CLIENT_ID_PREFIX = 'HUB'
  static SECRET_LENGTH = 32
  static API_KEY_TYPE = 'API_KEY'

  constructor (
    private readonly dynamodbClient: DynamoDBDocumentClient,
    private readonly apiGatewayClient: APIGatewayClient
  ) {}

  async call (fpoId: string): Promise<CustomerApiKey> {
    const customerApiKey = new CustomerApiKey()

    customerApiKey.FpoId = fpoId
    customerApiKey.CustomerApiKeyId = this.generateClientId()
    customerApiKey.Secret = await this.generateRandomSecret()
    customerApiKey.Enabled = true
    customerApiKey.Description = `Autogenerated on ${new Date().toISOString()}`

    await this.createInApiGateway(customerApiKey)
    await this.createInDynamoDb(customerApiKey)
    await this.associateToUsagePlan(customerApiKey)

    return customerApiKey
  }

  private async createInDynamoDb (customerApiKey: CustomerApiKey): Promise<void> {
    const command = new PutCommand({
      TableName: 'CustomerApiKeys',
      Item: customerApiKey.toItem()
    })

    const response = await this.dynamodbClient.send(command)

    if (response.$metadata.httpStatusCode === 201) {
      customerApiKey.Saved = true
    }
  }

  private async createInApiGateway (customerApiKey: CustomerApiKey): Promise<void> {
    const input: CreateApiKeyCommandInput = await customerApiKey.toApiGatewayItem()
    const command = new CreateApiKeyCommand(input)

    const response = await this.apiGatewayClient.send(command)

    customerApiKey.ApiGatewayId = response.id
  }

  private async associateToUsagePlan (customerApiKey: CustomerApiKey): Promise<void> {
    const input: CreateUsagePlanKeyRequest = {
      keyId: customerApiKey.ApiGatewayId,
      usagePlanId: process.env.USAGE_PLAN_ID,
      keyType: CreateCustomerApiKeyService.API_KEY_TYPE
    }

    const command = new CreateUsagePlanKeyCommand(input)

    await this.apiGatewayClient.send(command)
  }

  private generateClientId (): string {
    let clientId = CreateCustomerApiKeyService.CLIENT_ID_PREFIX

    for (let i = 0; i < CreateCustomerApiKeyService.CLIENT_ID_LENGTH; i++) {
      const randomIndex = Math.floor(Math.random() * CreateCustomerApiKeyService.CLIENT_ID_CHARS.length)

      clientId += CreateCustomerApiKeyService.CLIENT_ID_CHARS[randomIndex]
    }

    return clientId
  }

  private async generateRandomSecret (): Promise<string> {
    const randomSecret: string = crypto.randomBytes(CreateCustomerApiKeyService.SECRET_LENGTH).toString('base64')
    const encrypted = await new CustomerApiKeyEncryption().encrypt(randomSecret)

    return encrypted
  }
}

export { CreateCustomerApiKeyService }
